<?php

/**
 * @file
 * Page callbacks for self-assessment management and printing.
 */

/**
 * Form constructor for the assessment add/edit form.
 *
 * @param type $assessment
 *   A fully-loaded assessment object.
 *
 * @return
 *   The assessment add/edit form.
 */
function wic_nss_assessment_form($form, &$form_state, $assessment = NULL) {

}

/**
 * Page callback: Displays the add assessment form.
 */
function wic_nss_assessment_add_page() {

}

/**
 * Page callback: Displays the assessment management form.
 */
function wic_nss_assessment_default_page() {

}

/**
 * Page callback: Displays the delete assessment form.
 *
 * @param type $assessment
 *   A fully-loaded assessment object.
 */
function wic_nss_assessment_delete_confirm($form, &$form_state, $assessment) {

}

/**
 * Form submission handler for wic_nss_assessment_delete_confirm().
 *
 * @see wic_nss_assessment_delete_confirm()
 */
function wic_nss_assessment_delete_confirm_submit($form, &$form_state) {

}

/**
 * Page callback: Displays the edit assessment form.
 *
 * @param $assessment
 *   A fully-loaded assessment object.
 *
 * @return
 *   The assessment editing form.
 */
function wic_nss_assessment_edit_page($assessment) {

}
